name: Heartbeat_System

on:
  schedule:
    - cron: '0 * * * *' # Автозапуск каждый час в 00 минут
  workflow_dispatch:      # Кнопка ручного запуска в меню Actions

permissions:
  contents: write         # Даем боту право записывать файлы в твой репозиторий

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Matrix
        run: |
          gcc core.c -lm -o core
          ./core

      - name: Save State
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 1. Добавляем измененный лог в индекс
          git add matrix_state.log
          
          # 2. Подтягиваем изменения с сервера (если они были), разрешая конфликты в нашу пользу
          git pull origin main --rebase -X ours
          
          # 3. Делаем коммит и пушим только если есть изменения
          if ! git diff --cached --quiet; then
            git commit -m "Cycle Sync 13.10.1986 [$(date)]"
            git push origin main
          else
            echo "No changes to commit"
          fi
